// templates/reatom-ts/src/index.tsx
import { connectLogger } from '@reatom/framework'
import { ctx, mount } from '@reatom/jsx'

import { Counter } from './counter'
import style from './style.css?raw'

GM_addStyle(style)

if (import.meta.env.MODE === 'development') {
  connectLogger(ctx)
}

const target = document.querySelector('.card')
if (target) {
  mount(target, <Counter />)
}

// templates/solid/src/index.jsx
import { render } from 'solid-js/web'

import { Counter } from './counter'
import style from './style.css?raw'

const target = document.querySelector('.card')

if (target) {
  GM_addStyle(style)
  const fragment = document.createDocumentFragment()
  render(() => <Counter />, fragment)
  target.append(fragment)
}
